### PR TITLE
[Fix #244] Fix incompatibilities with python3

### LINKED ISSUE #244: Incompatible Python 3.6
Could you please update it?

Thank you for the job!

### PR DESCRIPTION
**Pull request by szobov**
Closes #244

Should work for both **python2** and **python3** version.
But need to be tested on both.

To test this feature you can use this link to install using Plugin Manager `install from URL`:
https://github.com/szobov/OctoPrint-Telegram/archive/fix-244-python3-incompat.zip

Or install from terminal (but check you're using the same version with which Octoprint has been installed):
```
python -m pip install https://github.com/szobov/OctoPrint-Telegram/archive/fix-244-python3-incompat.zip
```

Prev PR: #273 

Thanks.

### CODE REVIEW

**Comment by SM-26** [comment]
Tested on OctoPrint 1.4.2 Python 3.7.3 OctoPi 0.17.0 and everything is working flawlessly.

**Comment by giloser** [comment]
Thanks a lot!
I just install it and as far as I'm everything works, I'll start a print and comment again when it's finished.

**Comment by schwabe** [comment]
I used ` ./oprint/bin/pip3   install https://github.com/szobov/OctoPrint-Telegram/archive/fix-244-python3-incompat.zip` on my octopi system and it works fine here.

**Comment by MettyD** [comment]
It tested everything with Python2:
Result: Everything is working good, except the settings-command:
Logfile outputs the following message:
2020-10-05 12:26:28,709 - octoprint.plugins.telegram.listener - INFO - Got a command: '/settings' with parameter: '' in chat 340241802
2020-10-05 12:26:28,712 - octoprint.settings - WARNING - Could not convert '' to a valid integer when getting option [u'plugins', 'telegram', u'notification_time']
2020-10-05 12:26:28,715 - octoprint.settings - WARNING - Could not convert '' to a valid integer when getting option [u'plugins', 'telegram', u'notification_time']
2020-10-05 12:26:28,715 - octoprint.plugins.telegram.listener - ERROR - Exception caught! %d format: a number is required, not NoneType

anybody else with this problem ?

**Comment by giloser** [comment]
Hi there,

I'm currently testing the python 2 but didn't try that option before you point your problem and I don't have it.
Could you please give us more info about what you are trying to do? What system you are on(pi, PC,...) ?

thanks

**Comment by MettyD** [comment]
> Hi there,
> 
> I'm currently testing the python 2 but didn't try that option before you point your problem and I don't have it.
> Could you please give us more info about what you are trying to do? What system you are on(pi, PC,...) ?
> 
> thanks

I am on PI running the following:
model: Raspberry Pi 4 Model B Rev 1.2
octopi_version: 0.17.0
Python: pip: 19.3.1, version: 2.7.16

I simply installed the testversion and entered /settings as command. Output is nothing:
This results in the logentries given, i posted before

Any more infos needed ?

**Comment by MettyD** [comment]
> > Hi there,
> > I'm currently testing the python 2 but didn't try that option before you point your problem and I don't have it.
> > Could you please give us more info about what you are trying to do? What system you are on(pi, PC,...) ?
> > thanks
> 
> I am on PI running the following:
> model: Raspberry Pi 4 Model B Rev 1.2
> octopi_version: 0.17.0
> Python: pip: 19.3.1, version: 2.7.16
> 
> I simply installed the testversion and entered /settings as command. Output is nothing:
> This results in the logentries given, i posted before
> 
> Any more infos needed ?

Problem is solved ! thanks to @szobov ;)

**Pull request merged**
