### PR TITLE
Add TP Link

### PR DESCRIPTION
**Pull request by cpeuschel**
Hi! I have added a couple of functions to turn on off the printer via the API of the TP-Link Smart Plug (https://plugins.octoprint.org/plugins/tplinksmartplug/). 

Thank you, @db0nd for your implementation of the PSU Control plugin.

maybe you can tell me how i can add the if statement in the template.

### CODE REVIEW

**Comment by giloser** [comment]
I'm sorry but it seems there was a change in the space or something like that there is difference for almost every lines.

I cannot check the real change you did

**Comment by giloser** [comment]
by the way did you check this https://github.com/kantlivelong/OctoPrint-PSUControl/wiki/Scripts

seems like the PSucontrol can control TPlink plug so maybe it's not needed to add.

**Comment by BastR** [comment]
I use the TPlink plugin because it allows me to see the electrical power consumed by the printer whereas to my knowledge PSUcontrol cannot, so TPLINK support seems necessary to me.

**Comment by giloser** [comment]
hi there was too many change on this PR to use it but I did add some of the smart plug in the new 1.6.3 version and the tp link should work.
Let me know if that Works for you!

**Comment by BastR** [comment]
With TP-Link Smartplug plugin installed it doesn't work. The /on or /off command say "Something wrong, power off command failed."

**Comment by giloser** [comment]
ok Can you send a log just after you tried one of the command?

**Comment by BastR** [comment]
@giloser 
[octoprint.log](https://github.com/fabianonline/OctoPrint-Telegram/files/5937103/octoprint.log)

**Comment by giloser** [comment]
it seems it get a 404 response from the tp link what is the plugin name and version? maybe not the version with the list function yet

**Comment by BastR** [comment]
I use this: https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/releases/tag/0.9.26

**Comment by giloser** [comment]
yeah ok so it's what I was afraid of. I will put a failsafe to check the config directly if I can't get the list with the function this way it should work even way. But this will probably have to wait a little bit. If you really want to use it directly I would say you should install the plugin with the link of the current development version.

**Comment by BastR** [comment]
I installed the plugin today and unfortunately it doesn't work. I will wait, if you need a tester I am available with pleasure.

Thank you for your work

**Comment by giloser** [comment]
Hi,

can you try this version
https://github.com/giloser/OctoPrint-Telegram/archive/master.zip

thanks

**Comment by BastR** [comment]
[octoprint.log](https://github.com/fabianonline/OctoPrint-Telegram/files/5960148/octoprint.log)
 It doesn't work BUT now Telegram chat respond to my command.

I've made /on, /off with telegram then on & off with the TPlink plugin

**Comment by BastR** [comment]
The /off command works as expected! I’ve switched on the printer manually then send a /off command and it works

**Comment by giloser** [comment]
Ok sorry I check this and the on would try to turn the plug off for the tplink ... sorry.
I fix it you can try the same link to update once again please.

**Comment by BastR** [comment]
All commands work has expected 👌🏼

**Comment by giloser** [comment]
this has been done in #342

**Pull request closed without merging**
