### PR TITLE
Adding two new variables: {chamber_temp} and {chamber_target}.

### PR DESCRIPTION
**Pull request by alpxp**
They access the chamber temperature status provided by octopi.
I tested this on my setup and it works ok.

### CODE REVIEW

**Comment by rlogiacco** [comment]
@alpxp can you please clarify how do you get those injected? Are those RaspberryPI specific?

**Comment by alpxp** [comment]
> @alpxp can you please clarify how do you get those injected? Are those RaspberryPI specific?

Sure. I don't think this is specific to RaspberryPI. The chamber temperature is provided my Marlin and read by Octopi. I have one of [those](https://www.amazon.de/ROSENICE-Thermistoren-Drucker-Extruder-Anschlusskabel/dp/B01M9CB5NF/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=marlin+temperature&qid=1586423866&sr=8-3) attached to the one vacant thermistor port of my GT2560 board.
In `Configuration.h`:
`#define TEMP_SENSOR_CHAMBER 1
`
In `pins_GT2560_REV_A.h`:
`#define TEMP_CHAMBER_PIN    9
`
Maybe https://github.com/MarlinFirmware/Marlin/issues/973 is relevant.

**Comment by alpxp** [comment]
Why was this reverted, btw?

**Comment by alpxp** [comment]
@rlogiacco Why was this reverted, btw?

**Comment by rlogiacco** [comment]
it was failing on my system which doesn't have the additional temp sensor...

**Pull request merged**
