### PR TITLE
Added functions to turn ON and OFF the printer through API of the PSU…

### PR DESCRIPTION
**Pull request by db0nd**
Hi! I have added a couple of functions to turn on off the printer via the API of the [PSU Control plugin](https://github.com/kantlivelong/OctoPrint-PSUControl) .

### CODE REVIEW

**Comment by giloser** [comment]
Hi thanks for the code!

Could I ask you to add a check to see if the plugin is activate on the octoprint before trying to call the command?
something like `if self._plugin_manager.get_plugin("multicam",True)` but with the correct plugin name and maybe a message to say it's not activate on the system yet if it return false.

thanks

**Comment by db0nd** [comment]
> Could I ask you to add a check to see if the plugin is activate on the octoprint before trying to call the command?
> something like `if self._plugin_manager.get_plugin("multicam",True)` but with the correct plugin name and maybe a message to say it's not activate on the system yet if it return false.

Ok. I'll try. I thought about it. But I have little programming experience. And this is my first pull request on github. I apologize in advance for possible mistakes)).

PS: I guess I should also make a description of these functions in the readme?

**Comment by giloser** [comment]
> 
> 
> > Could I ask you to add a check to see if the plugin is activate on the octoprint before trying to call the command?
> > something like `if self._plugin_manager.get_plugin("multicam",True)` but with the correct plugin name and maybe a message to say it's not activate on the system yet if it return false.
> 
> Ok. I'll try. I thought about it. But I have little programming experience. And this is my first pull request on github. I apologize in advance for possible mistakes)).
> 
> PS: I guess I should also make a description of these functions in the readme?

No problem it was already very nice.

yes an explanation into the readme would be also very nice!

**Comment by db0nd** [comment]
I redid

**Comment by giloser** [comment]
great thanks I'll try to merge that before the next update

**Pull request merged**
