### PR TITLE
Issue #146 - Rotate 90 should be 270

### PR DESCRIPTION
**Pull request by alexisml**
Rotation of image should be COUNTER clockwise. Right now it's rotating 90 clockwise, so i'm changing that to 270 clockwise (i.e. 90 counter clockwise).

### CODE REVIEW

**Comment by GilDev** [comment]
Could this please be merged?

**Comment by GilDev** [comment]
I’ve installed the current master branch but the webcam feed is still upside down in Telegram… 😕

**Comment by alexisml** [comment]
> I’ve installed the current master branch but the webcam feed is still upside down in Telegram… 😕

You should see it exactly the same way as it's shown in frontend with this fix. It's working for me (I actually installed the plugin from my branch months ago).

**Comment by GilDev** [comment]
Well with version 1.4.3rc2 it’s upside down in Telegram but upright on the web interface. I have all options checked: “Flip webcam horizontally”, “Flip webcam vertically” and “Rotate webcam 90 degrees counter clockwise”.

**Comment by rlogiacco** [comment]
please see #146 for my comment, but you need to update again the plugin first

**Comment by GilDev** [comment]
There you go:

```
2019-07-22 19:05:56,595 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-07-22 19:05:56,688 - octoprint.plugins.telegram - DEBUG - Image transformations [H:True, V:True, R:True]
2019-07-22 19:05:56,776 - octoprint.plugins.telegram - DEBUG - data so far: {'disable_web_page_preview': True}
2019-07-22 19:05:56,777 - octoprint.plugins.telegram - DEBUG - Sending with image.. 236639344
2019-07-22 19:05:57,506 - octoprint.plugins.telegram - DEBUG - Sending finished. 200
2019-07-22 19:05:57,508 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 146854221...
```

Also, on a fresh new install on a Raspberry Pi 4 with Telegram Plugin 1.4.3rc3, the plugin launches the wizard asking for the Telegram bot’s token at each startup.
Still an upside down image on Telegram but not on the web interface though.

**Comment by rlogiacco** [comment]
From the logs it clearly appears your settings are interpreted correctly by the plugin, so something else must be at play here...
Next attempt is probably to save the image somewhere before applying the transformations and after, to check if the two differs...
Also the token requested at each startup doesn’t seem right, but let’s focus on one issue at a time

**Comment by alnavasa** [comment]
Still no solution for this?

**Pull request merged**
